### PR TITLE
fixing mkstemp without securely setting mask/unmask

### LINKED ISSUE #101: Calling "mkstemp" without securely setting umask first
Using mkstemp without setting the permission mask with umask harmful.
https://github.com/ros/rospack/blob/3358d21fbeb5355a459e94354c2aa95e0a376e57/src/rospack.cpp#L2064

### PR DESCRIPTION
**Pull request by danielwangksu**
fix https://github.com/ros/rospack/issues/101

In newer glibc's (versions > 2.06) reasonably secure permissions of 0600 are used when creating a temporary file with mkstemp(). But for older glibc and other platform this is not guaranteed.

Signed-off-by: Daniel Wang <daniel.wang@canonical.com>

### CODE REVIEW

File: src/rospack.cpp [hunk 1]
```diff
@@ -2061,7 +2061,9 @@ Rosstackage::writeCache()
     {
       FILE *cache = fopen(tmp_cache_path, "w");
 #else
+    mode_t mask = umask(S_IRUSR | S_IWUSR| S_IXUSR | S_IRWXG);
```
Comment (dirk-thomas) [inline src/rospack.cpp]: Your description mentioned 0600. Is that not a desired mask? Why also add read, write, execute/search for the group?

Is there a reason not to use `S_IRWXU` as a shortcut for the first three flags?

Comment (danielwangksu) [reply src/rospack.cpp]: Good point I will change it to `S_IRWXU`, I think default 0600 should be sufficient, but I'm not sure if any process requires read, write, execute group permission for concurrency. If not I will remove it. Thank you for your response

**Comment by kyrofa** [comment]
@dirk-thomas this is ready for another pass when you're able.

**Comment by dirk-thomas** [comment]
Thanks for the patch.

**Comment by dirk-thomas** [comment]
This patch broke the behavior since new cache files are currently created with a mask of `0` and are therefore not readable. See #117 for the bug report.
